### ISSUE TITLE
plans to add examples? tentative roadmap?

### ISSUE THREAD

**Issue by marco-m** [jba/xltest#1]
Hello Jonathan,
having used TAP in the past (and loving Go and using [rogpeppe/go-internal/testscript](https://github.com/rogpeppe/go-internal/tree/master/testscript)), I see the potential for this approach :-)

I was wondering if you had a plan to add minimal examples, and in general if you had a sort of tentative roadmap for xltest?

thanks!

**Comment by jba** [comment]
I just did a push. You can find examples in `testdata`. 

There are a couple of projects I plan to use it for and it may grow from that, but I have no further plans, except to add more languages and improve the ones I have currently. I want to keep it dead simple. Every new feature has to be implemented N times.

**Comment by marco-m** [comment]
Thanks!

> I want to keep it dead simple.

I understand perfectly :-)
